version: "3.7"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker/docker-entrypoint-initdb:/docker-entrypoint-initdb.d:ro
  web:
    depends_on:
      - postgres
